# Generated by Django 5.2.17 on 2026-09-21 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('sector', models.CharField(max_length=100)),
                ('project_type', models.CharField(default='New manufacturing unit', max_length=100)),
                ('location', models.CharField(max_length=120)),
                ('district', models.CharField(blank=True, max_length=120)),
                ('state', models.CharField(default='Maharashtra', max_length=80)),
                ('investment_amount', models.BigIntegerField(default=0)),
                ('employee_count', models.PositiveIntegerField(default=0)),
                ('is_midc', models.BooleanField(default=False)),
                ('land_status', models.CharField(default='To be confirmed', max_length=80)),
                ('power_requirement', models.CharField(blank=True, max_length=80)),
                ('environmental_category', models.CharField(default='To be confirmed', max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('status', models.CharField(default='Missing', max_length=40)),
                ('file', models.FileField(blank=True, upload_to='documents/')),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.project')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_name', models.CharField(max_length=160)),
                ('status', models.CharField(default='draft', max_length=40)),
                ('readiness', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='core.project')),
            ],
        ),
    ]
